name: Build and Deploy

on:
  workflow_dispatch: {}
  push: 
    branches:
      - main
  
env:
  workfolder: rathena

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Build action step
        id: package
        working-directory: ${{ env.workfolder }}
        run: ./builder.sh
      
      - name: Update permissions
        run: chmod +x  ${{ env.workfolder }}/login-server && chmod +x  ${{ env.workfolder }}/login-server && chmod +x  ${{ env.workfolder }}/login-server
      
      - name: Package the required files in an archive
        run: mkdir packaged-rtm && mkdir packaged-rtm/log && mv ${{ env.workfolder }}/login-server ${{ env.workfolder }}/map-server ${{ env.workfolder }}/char-server ${{ env.workfolder }}/athena-start ${{ env.workfolder }}/function.sh ${{ env.workfolder }}/conf/ ${{ env.workfolder }}/db/ ${{ env.workfolder }}/npc/ packaged-rtm/ && tar -zcvf packaged-rtm.tar.gz packaged-rtm
      
      - name: Place the archive in a folder to upload
        run: mkdir compressed && mv packaged-rtm.tar.gz compressed

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: compressed
          destination_dir: compressed-rtm
