name: Build and Deploy

on:
  workflow_dispatch: {}
  push: 
    branches:
      - aws
  
env:
  workfolder: rathena

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: jirutka/setup-alpine@v1.2.0
        with:
          branch: v3.18
          packages: wget git cmake make gcc g++ gdb zlib-dev mariadb-dev ca-certificates linux-headers bash valgrind netcat-openbsd

      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Build action step
        id: package
        working-directory: ${{ env.workfolder }}
        run: ./builder.sh
      
      - name: Package the required files in an archive
        run: mkdir packaged-rtm && mv ${{ env.workfolder }}/login-server ${{ env.workfolder }}/map-server ${{ env.workfolder }}/char-server ${{ env.workfolder }}/conf/ ${{ env.workfolder }}/db/ ${{ env.workfolder }}/npc/ packaged-rtm/ && tar -zcvf packaged-rtm.tar.gz packaged-rtm && ls -l

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: packaged-rtm.tar.gz
          destination_dir: packaged-rtm
