name: Build and Deploy

on:
  workflow_dispatch: {}
  push: 
    branches:
      - aws
  
env:
  workfolder: rathena/

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: jirutka/setup-alpine@v1.2.0
        with:
          packages: wget git cmake make gcc g++ gdb zlib-dev mariadb-dev ca-certificates linux-headers bash valgrind netcat-openbsd

      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Build action step
        id: package
        working-directory: rathena/
        run: pwd && ls -l && ./builder.sh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packaged-rtm/
          path: |
            login-server
            map-server
            char-server
            conf/
            db/
            npc/

  upload:
    needs: build
    runs-on: ubuntu-latest
    environment: Dev
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v4
      with:
        name: packaged-rtm
    - uses: shallwefootball/s3-upload-action@master
      name: Upload S3
      id: S3
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: 'packaged-rtm'
        destination_dir: 'packaged-rtm'  
    # Delete artifact
    - uses: geekyeggo/delete-artifact@v5
      with:
        name: packaged-rtm/
